devices:
- id: "parking_beacon"
  name: "Parking Beacon"
  source: "advertisement"
  match:
    manufacturer_id: 861
    manufacturer_hex_prefix: "04"
  instance_mode: "shared"
  sensors:
  - key: "parking_time"
    device_class: "timestamp"
    icon: "mdi:clock-time-four-outline"
    source_field: "manufacturer_data"
    length: 14
    decode:
      offset: 7
      length: 4
      type: "timestamp"
  - key: "parking_floor"
    icon: "mdi:layers-outline"
    accuracy_decimals: 0
    source_field: "manufacturer_data"
    length: 14
    decode:
      offset: 11
      scale: -1.0
      offset_value: 256.0
  - key: "parking_location"
    platform: "text_sensor"
    icon: "mdi:map-marker-outline"
    source_field: "manufacturer_data"
    length: 14
    decode:
      offset: 12
      length: 2
      type: "string"
- id: "apt_key_door"
  name: "APT Door Event"
  source: "advertisement"
  match:
    manufacturer_id: 861
    manufacturer_hex_prefix: "02"
  instance_mode: "shared"
  sensors:
  - key: "door_status"
    platform: "text_sensor"
    icon: "mdi:door"
    source_field: "manufacturer_data"
    length: 6
    decode:
      offset: 4
      map:
        "65": "entering"
        "1": "entering"
        "64": "exiting"
        "0": "idle"
    publish:
      min_interval: "1s"
- id: "car_obd"
  name: "2023 Volkswagen ID.4"
  source: "obd"
  obd:
    service_uuid: "18F0"
    tx_char_uuid: "2AF1"
    rx_char_uuid: "2AF0"
    tx_delay: "100ms"
    init_commands:
    - "ATSP7"
    - "ATCP17"
    - "ATSHFC007B"
    - "ATCAF1"
    - "ATCFC1"
    - "ATCRA17FE007B"
  sensors:
  - key: "battery_soc_bms"
    device_class: "battery"
    unit: "%"
    state_class: "measurement"
    icon: "mdi:battery"
    accuracy_decimals: 1
    mode: "22"
    pid: "028C"
    formula: "a/2.5"
    update_interval: "10s"
    publish:
      min_interval: "10s"
      deadband: 0.1
      heartbeat: "5m"
- id: "veepeak"
  name: "VEEPEAK"
  source: "advertisement"
  match:
    mac: "8C:DE:52:DA:F9:2B"
    name_prefix: "VEEPEAK"
  sensors:
  - key: "value"
    state_class: "measurement"
    accuracy_decimals: 1
    min_length: 2
    decode:
      length: 2
      type: "int16"
      scale: 0.1
